### ISSUE TITLE
Docstring clarification

### ISSUE THREAD

**Issue by TheChymera** [IBT-FMI/COSgen#4]
1. Could you please clarify the following section of the docstring? https://github.com/IBT-FMI/COSgen/blob/d68af52cb50e77ba6f476eeb0053618fa1d54805/cosgen/function_crate.py#L207-L211 I assume it's just a typo as/has --- but I still don't understand where a crossover function would be specified, and what it means to have it fixed to this function.

2. https://github.com/IBT-FMI/COSgen/blob/d68af52cb50e77ba6f476eeb0053618fa1d54805/cosgen/models.py#L133-L135 This needs commas for the ennumeration, and *vectors has a typo, but most importantly: would linearly decaying time course not be a better description? Same here:
https://github.com/IBT-FMI/COSgen/blob/d68af52cb50e77ba6f476eeb0053618fa1d54805/cosgen/models.py#L230-L232

3. Unsure what cave means here: https://github.com/IBT-FMI/COSgen/blob/d68af52cb50e77ba6f476eeb0053618fa1d54805/cosgen/models.py#L456

**Comment by faymanns** [comment]
I think I fixed them all.
Not sure if the first one is clear now:
https://github.com/IBT-FMI/COSgen/blob/c9f980cd3271d3c57f9df16ecd462590eaac1859/cosgen/function_crate.py#L205-L211

**Comment by TheChymera** [comment]
Yes, it's still not very clear what is set to which function, and what being set means. Do you mean the argument is passed to another function? as a **keyword argument?
